experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_elliot.tsv
    validation_path: ../data/{0}/val_elliot.tsv
    test_path: ../data/{0}/test_elliot.tsv
  dataset: amazon-book
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.ContextGNN:
      meta:
        hyper_opt_alg: grid
        verbose: False
        save_weights: True
        save_resume: True
        validation_rate: 1
        validation_metric: Recall@20
        restore: True
        write_best_iterations: True

      # TRAINING
      epochs: 999
      max_steps: 2000
      lr: 0.001
      acc_steps: 4
      batch_size: 32 # 128/acc_steps
      eval_batch_size: 32
      inference_for_ranking: full,global,local
      seed: 0

      # EARLY STOPPING
      early_stopping:
        monitor: Recall@20
        min_delta: 0
        patience: 10
        verbose: True
        mode: auto

      # ARCHITECTURE
      gnn: GraphSAGE
      loss: ce
      n_layers: 4
      aggr: sum
      factors: 128
      channels: 128
      neigh: (16,16,8,8)

      # SGL & XSimGCL
      cl_method: none # none | sgl | xsimgcl
      lambda_cl: 0.0
      tau_cl: 0.2
      cl_layer: 2

      # SGL
      # edge_drop_p: 0.1

      # XSimGCL
      # xsim_eps: 0.1